"""
MCP Server for AgentChatBus.

Registers Tools, Resources, and Prompts as defined in the plan.
Mounted onto the FastAPI app via SSE transport.
"""
import json
import asyncio
import logging
import uuid
import time
from urllib.parse import parse_qs
from contextvars import ContextVar
from typing import Any

import mcp.types as types
from mcp.server import Server
from mcp.server.sse import SseServerTransport

from src.db.database import get_db
from src.db import crud
from src.config import BUS_VERSION, HOST, PORT, MSG_WAIT_TIMEOUT, EXPOSE_THREAD_RESOURCES

logger = logging.getLogger(__name__)

# Per-connection language preference.
# Set in `mcp_sse_endpoint` from the ?lang= query parameter.
# Each SSE connection runs in its own asyncio Task, so ContextVar isolates
# concurrent clients: Cursor speaks Chinese while Claude Desktop speaks Japanese.
_session_language: ContextVar[str | None] = ContextVar("session_language", default=None)

# Per-connection session ID (UUID-like identifier for the SSE connection).
# Set in `mcp_sse_endpoint` to uniquely identify each SSE connection.
_session_id: ContextVar[str | None] = ContextVar("session_id", default=None)

import threading

# Global map from thread identifier to current SSE session ID (for cross‑thread ContextVar fallback).
_thread_session_map: dict[int, str] = {}

def init_session_id() -> str:
    """Initialize a new session ID for this SSE connection."""
    session_id = str(uuid.uuid4())
    _session_id.set(session_id)
    # Record thread → session mapping for fallback.
    _thread_session_map[threading.get_ident()] = session_id
    return session_id

# Per-connection agent identity.
# Set when agent registers, heartbeats, or resumes. Used for auto-tracking activity.
_current_agent_id: ContextVar[str | None] = ContextVar("current_agent_id", default=None)
_current_agent_token: ContextVar[str | None] = ContextVar("current_agent_token", default=None)

# Connection-level agent registry.
# Maps session_id -> {"agent_id": ..., "token": ...}
# Populated when agent_register/resume is called, used by msg_wait for auto-tracking.
_connection_agents: dict[str, dict[str, str]] = {}

# Live SSE session registry (in-memory only, resets on server restart).
# Contains session_ids that currently have an active SSE TCP connection.
# Sessions are refreshed on each tool call POST and during msg_wait heartbeats.
# After the last refresh, sessions are considered stale after _SSE_STALE_SECONDS.
# Kept deliberately short (60s) so that agents go offline quickly after msg_wait
# ends or they stop making tool calls, rather than staying "live" for 5+ minutes.
_active_sse_sessions: dict[str, float] = {}
_SSE_STALE_SECONDS = 60
def get_session_id() -> str | None:
    """Get session ID for this SSE connection."""
    return _session_id.get()


def bind_session_id_from_scope(scope: dict[str, Any]) -> str | None:
    """Bind `_session_id` from an incoming ASGI HTTP scope.

    MCP SSE clients post JSON-RPC messages to `/mcp/messages` and include
    session identity in query/header depending on client/server transport.
    Tool handlers (agent_register/resume/heartbeat/msg_wait) run in the
    request context of that POST, so we must restore session id there.
    """
    try:
        query_string = scope.get("query_string", b"")
        if isinstance(query_string, bytes):
            query_string = query_string.decode("utf-8", errors="ignore")
        query = parse_qs(query_string or "")

        session_id = (
            (query.get("session_id") or [None])[0]
            or (query.get("sessionId") or [None])[0]
            or (query.get("sid") or [None])[0]
        )

        if not session_id:
            headers = dict(scope.get("headers") or [])
            raw = headers.get(b"x-session-id") or headers.get(b"mcp-session-id")
            if raw:
                session_id = raw.decode("utf-8", errors="ignore").strip()

        if not session_id:
            return None

        _session_id.set(session_id)
        _thread_session_map[threading.get_ident()] = session_id
        mark_sse_connected(session_id)
        return session_id
    except Exception:
        return None


def bind_session_id_from_request_context() -> str | None:
    """Bind session id from MCP `server.request_context` if available.

    Tool handlers execute under MCP request context; this is the most reliable
    place to read the POST `/mcp/messages?...` query parameter that carries the
    real session_id generated by SseServerTransport.
    """
    try:
        request = server.request_context.request
    except Exception:
        return None

    try:
        session_id = None
        query = getattr(request, "query_params", None)
        if query is not None:
            session_id = query.get("session_id") or query.get("sessionId") or query.get("sid")

        if not session_id:
            headers = getattr(request, "headers", None)
            if headers is not None:
                session_id = headers.get("x-session-id") or headers.get("mcp-session-id")

        if not session_id:
            return None

        session_id = str(session_id).strip()
        if not session_id:
            return None

        _session_id.set(session_id)
        _thread_session_map[threading.get_ident()] = session_id
        mark_sse_connected(session_id)
        return session_id
    except Exception:
        return None

def set_connection_agent(agent_id: str, token: str) -> None:
    """Store agent identity for this connection.

    If the ContextVar `_session_id` is unavailable (e.g., because the call is
    executed in a different thread), we fall back to the thread‑session map.
    """
    bind_session_id_from_request_context()
    session_id = get_session_id()
    if not session_id:
        # Fallback: try thread‑local mapping.
        session_id = _thread_session_map.get(threading.get_ident())
    if not session_id:
        logger.warning("[set_connection_agent] No session ID available, skipping")
        return
    _connection_agents[session_id] = {"agent_id": agent_id, "token": token}
    logger.info(f"[connection_agent] stored for session {session_id[:8]}: agent_id={agent_id}")

def get_connection_agent() -> tuple[str | None, str | None]:
    """Retrieve stored agent identity for this connection."""
    bind_session_id_from_request_context()
    session_id = get_session_id()
    if not session_id:
        return None, None
    agent_info = _connection_agents.get(session_id)
    if agent_info:
        logger.info(f"[get_connection_agent] retrieved from session {session_id[:8]}: agent_id={agent_info['agent_id']}")
        return agent_info["agent_id"], agent_info["token"]
    return None, None

def get_agent_for_session(session_id: str | None) -> str | None:
    """Retrieve agent_id for a given session_id (independent of current context)."""
    if not session_id:
        return None
    agent_info = _connection_agents.get(session_id)
    return agent_info.get("agent_id") if agent_info else None

def pop_agent_for_session(session_id: str | None) -> tuple[str | None, str | None]:
    """Remove and return (agent_id, token) for a session. Called on disconnect."""
    if not session_id:
        return None, None
    agent_info = _connection_agents.pop(session_id, None)
    if agent_info:
        logger.info(f"[pop_agent] removed from session {session_id[:8]}: agent_id={agent_info['agent_id']}")
        return agent_info["agent_id"], agent_info["token"]
    return None, None


def mark_sse_connected(session_id: str) -> None:
    """Mark this SSE session as having a live TCP connection."""
    _active_sse_sessions[session_id] = time.time()


def mark_sse_disconnected(session_id: str) -> None:
    """Remove the SSE session from the live-connection registry.

    Also cleans up the thread‑session fallback map.
    """
    _active_sse_sessions.pop(session_id, None)
    # Remove any thread mapping that points to this session.
    for tid, sid in list(_thread_session_map.items()):
        if sid == session_id:
            del _thread_session_map[tid]


def is_agent_sse_connected(agent_id: str) -> bool:
    """Return True if this agent has a live SSE connection.

    The agent must have a registered session in `_connection_agents` *and* that
    session must be present in `_active_sse_sessions`.
    """
    now = time.time()
    stale_sessions = [sid for sid, ts in _active_sse_sessions.items() if now - ts > _SSE_STALE_SECONDS]
    for sid in stale_sessions:
        _active_sse_sessions.pop(sid, None)
        _connection_agents.pop(sid, None)

    return any(
        info.get("agent_id") == agent_id and sid in _active_sse_sessions
        for sid, info in _connection_agents.items()
    )

# Create the MCP server instance
server = Server("AgentChatBus")


# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
# TOOLS
# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ

@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        # ΓöÇΓöÇ Thread Management ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
        types.Tool(
            name="thread_create",
            description=(
                "Create a new conversation thread (topic / task context) on the bus. "
                "Authentication is mandatory: provide creator credentials explicitly in input "
                "using `agent_id` and `token` (you can obtain them from agent_register/agent_resume). "
                "Returns thread details plus initial sync context "
                "(`current_seq`, `reply_token`, `reply_window`) for the creator's first msg_post."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "topic":         {"type": "string", "description": "Short description of the thread's purpose."},
                    "agent_id":      {"type": "string", "description": "Creator agent id. Required."},
                    "token":         {"type": "string", "description": "Creator token for authentication. Required."},
                    "metadata":      {"type": "object", "description": "Optional arbitrary key-value metadata."},
                    "system_prompt": {"type": "string", "description": "Optional system prompt defining collaboration rules for this thread. Overrides template default."},
                    "template":      {"type": "string", "description": "Template ID to apply defaults (system_prompt, metadata). Caller-provided values take precedence."},
                },
                "required": ["topic", "agent_id", "token"],
            },
        ),
        types.Tool(
            name="thread_list",
            description=(
                "List threads, optionally filtered by status. "
                "Supports cursor pagination via `limit` and `before`. "
                "Returns an envelope with `threads`, `total`, `has_more`, and `next_cursor`."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "status": {"type": "string", "enum": ["discuss", "implement", "review", "done", "closed", "archived"],
                               "description": "Filter by lifecycle state. Omit for all threads."},
                    "include_archived": {
                        "type": "boolean",
                        "default": False,
                        "description": "If true and no status filter is provided, include archived threads.",
                    },
                    "limit": {
                        "type": "integer",
                        "default": 0,
                        "description": "Max threads to return. 0 means all (no limit). Hard cap: 200.",
                    },
                    "before": {
                        "type": "string",
                        "description": (
                            "Pagination cursor: ISO datetime string. "
                            "Returns threads created strictly before this timestamp. "
                            "Pass `next_cursor` from a previous response to fetch the next page."
                        ),
                    },
                },
            },
        ),
        types.Tool(
            name="thread_delete",
            description=(
                "Permanently delete a thread and ALL its messages. IRREVERSIBLE — data cannot be recovered. "
                "Prefer thread_archive for reversible removal. "
                "Requires confirm=true to proceed."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_id": {"type": "string", "description": "ID of the thread to delete."},
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to proceed. Safeguard against accidental deletion.",
                    },
                },
                "required": ["thread_id", "confirm"],
            },
        ),
        types.Tool(
            name="thread_get",
            description="Get details of a single thread by ID.",
            inputSchema={
                "type": "object",
                "properties": {"thread_id": {"type": "string"}},
                "required": ["thread_id"],
            },
        ),


        # ΓöÇΓöÇ Messaging ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
        types.Tool(
            name="msg_post",
            description="Post a message to a thread. Returns the new message ID and global seq number.",
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_id": {"type": "string"},
                    "author":    {"type": "string", "description": "Agent ID, 'system', or 'human'."},
                    "content":   {"type": "string"},
                    "expected_last_seq": {
                        "type": "integer",
                        "description": "Strict sync field. Thread seq the sender used as context baseline.",
                    },
                    "reply_token": {
                        "type": "string",
                        "description": "Strict sync field. Unconsumed reply token from thread_create/msg_wait/sync-context.",
                    },
                    "role":      {"type": "string", "enum": ["user", "assistant", "system"], "default": "user"},
                    "priority":  {
                        "type": "string",
                        "enum": ["normal", "urgent", "system"],
                        "default": "normal",
                        "description": "Message priority level. 'urgent' for time-sensitive content, 'system' for automated coordination messages.",
                    },
                    "mentions":  {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of agent IDs to mention in this message."
                    },
                    "metadata":  {
                        "type": "object",
                        "description": "Structured message metadata for orchestration and routing.",
                        "properties": {
                            "handoff_target": {
                                "type": "string",
                                "description": "Agent ID that should handle this message next (triggers msg.handoff SSE event).",
                            },
                            "stop_reason": {
                                "type": "string",
                                "enum": ["convergence", "timeout", "error", "complete", "impasse"],
                                "description": "Why the posting agent is ending its turn (triggers msg.stop SSE event).",
                            },
                            "attachments": {
                                "type": "array",
                                "items": {"type": "object"},
                                "description": "File or image attachments.",
                            },
                        },
                    },
                    "reply_to_msg_id": {
                        "type": "string",
                        "description": "Optional ID of the message being replied to. Must belong to the same thread. Triggers a msg.reply SSE event.",
                    },
                },
                "required": ["thread_id", "author", "content", "expected_last_seq", "reply_token"],
            },
        ),
        types.Tool(
            name="msg_list",
            description="Fetch messages in a thread after a given seq cursor.",
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_id": {"type": "string"},
                    "after_seq": {"type": "integer", "default": 0, "description": "Return messages with seq > this value."},
                    "limit":     {"type": "integer", "default": 100},
                    "priority":  {
                        "type": "string",
                        "enum": ["normal", "urgent", "system"],
                        "description": "Optional: filter messages by priority level.",
                    },
                    "return_format": {
                        "type": "string",
                        "enum": ["json", "blocks"],
                        "default": "blocks",
                        "description": (
                            "Return format for tool result content. "
                            "'blocks' returns native MCP content blocks (TextContent/ImageContent...). "
                            "'json' returns a single JSON-encoded text payload (legacy)."
                        ),
                    },
                    "include_system_prompt": {
                        "type": "boolean",
                        "default": True,
                        "description": "If true and after_seq=0, prepend a synthetic system prompt row.",
                    },
                },
                "required": ["thread_id"],
            },
        ),
        types.Tool(
            name="msg_get",
            description=(
                "Fetch a single message by its ID. "
                "Returns full message details including content, author, seq, priority, "
                "reply_to_msg_id, metadata, and reactions. "
                "Returns {found: false} if the message does not exist. "
                "Useful for reply-to context lookup, verification before reacting, "
                "or retrieving a specific message referenced by ID."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "message_id": {"type": "string", "description": "ID of the message to fetch."},
                },
                "required": ["message_id"],
            },
        ),
        types.Tool(
            name="msg_wait",
            description=(
                "Block until at least one new message arrives in the thread after `after_seq`. "
                "Returns immediately if messages are already available. "
                "Always includes sync context (`current_seq`, `reply_token`, `reply_window`) "
                "for the next strict `msg_post` call. "
                "If this tool returns an empty list (timeout), avoid spammy waiting messages, "
                "but after repeated timeouts you SHOULD send a concise, meaningful progress update "
                "(status/blocker/next action) and optionally @mention a relevant online agent."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_id":   {"type": "string"},
                    "after_seq":   {"type": "integer"},
                    "timeout_ms":  {"type": "integer", "default": 300000, "description": "Max wait in milliseconds."},
                    "return_format": {
                        "type": "string",
                        "enum": ["json", "blocks"],
                        "default": "blocks",
                        "description": (
                            "Return format for tool result content. "
                            "'blocks' returns native MCP content blocks (TextContent/ImageContent...). "
                            "'json' returns a single JSON-encoded text payload (legacy)."
                        ),
                    },
                    "agent_id":    {"type": "string", "description": "Optional: your agent ID for activity tracking."},
                    "token":       {"type": "string", "description": "Optional: your agent token for verification."},
                    "for_agent":   {
                        "type": "string",
                        "description": "Only return messages where metadata.handoff_target matches this agent ID. Useful for directed handoff routing.",
                    },
                },
                "required": ["thread_id", "after_seq"],
            },
        ),

        # ── Thread Templates (UP-18) ──────────────────────────────────────────
        types.Tool(
            name="template_list",
            description="List all available thread templates (built-in + custom).",
            inputSchema={"type": "object", "properties": {}},
        ),
        types.Tool(
            name="template_get",
            description="Get details of a specific thread template by ID.",
            inputSchema={
                "type": "object",
                "properties": {
                    "template_id": {"type": "string", "description": "Template ID to retrieve."},
                },
                "required": ["template_id"],
            },
        ),
        types.Tool(
            name="template_create",
            description="Create a custom thread template. Built-in templates cannot be overwritten.",
            inputSchema={
                "type": "object",
                "properties": {
                    "id":               {"type": "string", "description": "Unique slug ID for the template (e.g. 'my-review')."},
                    "name":             {"type": "string", "description": "Human-readable display name."},
                    "description":      {"type": "string", "description": "Short description of when to use this template."},
                    "system_prompt":    {"type": "string", "description": "Default system prompt applied when creating a thread with this template."},
                    "default_metadata": {"type": "object", "description": "Default metadata applied when creating a thread with this template."},
                },
                "required": ["id", "name"],
            },
        ),

        # ΓöÇΓöÇ Agent Identity & Presence ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
        types.Tool(
            name="agent_register",
            description=(
                "Register an agent onto the bus. The display name is auto-generated as "
                "'IDE (Model)' — e.g. 'Cursor (GPT-4)'. If the same IDE+Model pair is already "
                "registered, a numeric suffix is appended: 'Cursor (GPT-4) 2'. "
                "Optional `display_name` can be provided as a human-friendly alias. "
                "Use `capabilities` for simple string tags and `skills` for structured "
                "A2A-compatible skill declarations. "
                "Returns agent_id and a secret token for subsequent calls."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "ide":          {"type": "string",
                                     "description": "Name of the IDE or client, e.g. 'Cursor', 'Claude Desktop', 'CLI'."},
                    "model":        {"type": "string",
                                     "description": "Model name, e.g. 'claude-3-5-sonnet-20241022', 'GPT-4'."},
                    "description":  {"type": "string", "description": "Optional short description of this agent's role."},
                    "capabilities": {"type": "array", "items": {"type": "string"},
                                     "description": "Simple capability tags for fast matching, e.g. ['code', 'review', 'security']."},
                    "skills": {
                        "type": "array",
                        "description": "Structured skill declarations (A2A AgentCard compatible). Each skill has id and name at minimum.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id":          {"type": "string", "description": "Machine-readable skill identifier, e.g. 'code-review'."},
                                "name":        {"type": "string", "description": "Human-readable skill name."},
                                "description": {"type": "string", "description": "What this skill does."},
                                "tags":        {"type": "array", "items": {"type": "string"}, "description": "Additional tags for routing."},
                                "examples":    {"type": "array", "items": {"type": "string"}, "description": "Example prompts this skill handles."},
                            },
                            "required": ["id", "name"],
                        },
                    },
                    "display_name": {"type": "string", "description": "Optional human-friendly alias shown in UI and message labels."},
                },
                "required": ["ide", "model"],
            },
        ),
        types.Tool(
            name="agent_heartbeat",
            description="Send a keep-alive ping. Agents that miss the heartbeat window are marked offline.",
            inputSchema={
                "type": "object",
                "properties": {
                    "agent_id": {"type": "string"},
                    "token":    {"type": "string"},
                },
                "required": ["agent_id", "token"],
            },
        ),
        types.Tool(
            name="agent_resume",
            description="Resume a previously registered agent session using saved agent_id and token. Preserves all identity fields (name, alias, etc.). Returns agent details with online status. Fails if agent_id not found or token invalidΓÇöprovide correct credentials and retry.",
            inputSchema={
                "type": "object",
                "properties": {
                    "agent_id": {"type": "string"},
                    "token":    {"type": "string"},
                },
                "required": ["agent_id", "token"],
            },
        ),
        types.Tool(
            name="agent_unregister",
            description="Gracefully deregister an agent from the bus.",
            inputSchema={
                "type": "object",
                "properties": {
                    "agent_id": {"type": "string"},
                    "token":    {"type": "string"},
                },
                "required": ["agent_id", "token"],
            },
        ),
        types.Tool(
            name="agent_list",
            description=(
                "List all registered agents with online status, capabilities, and skills. "
                "Each entry includes `capabilities` (string tag array) and `skills` (structured A2A skill array) "
                "when declared at registration or via `agent_update`."
            ),
            inputSchema={"type": "object", "properties": {}},
        ),
        types.Tool(
            name="agent_update",
            description=(
                "Update mutable agent metadata after registration. "
                "Requires the original agent_id and token. "
                "Only provided fields are modified; omitted fields are left unchanged. "
                "Useful for adding or changing capabilities, skills, description, or display_name "
                "without re-registering."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "agent_id":     {"type": "string", "description": "The agent's ID returned by agent_register."},
                    "token":        {"type": "string", "description": "The secret token returned by agent_register."},
                    "description":  {"type": "string", "description": "Updated description of this agent's role."},
                    "display_name": {"type": "string", "description": "Updated human-friendly alias."},
                    "capabilities": {"type": "array", "items": {"type": "string"},
                                     "description": "Updated capability tags (replaces existing list)."},
                    "skills": {
                        "type": "array",
                        "description": "Updated skill declarations — replaces the existing list.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id":          {"type": "string"},
                                "name":        {"type": "string"},
                                "description": {"type": "string"},
                                "tags":        {"type": "array", "items": {"type": "string"}},
                                "examples":    {"type": "array", "items": {"type": "string"}},
                            },
                            "required": ["id", "name"],
                        },
                    },
                },
                "required": ["agent_id", "token"],
            },
        ),
        types.Tool(
            name="agent_set_typing",
            description="Broadcast an 'is typing' signal for a thread (optional, for UI feedback).",
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_id":  {"type": "string"},
                    "agent_id":   {"type": "string"},
                    "is_typing":  {"type": "boolean"},
                },
                "required": ["thread_id", "agent_id", "is_typing"],
            },
        ),

        # ── Reactions (UP-13) ────────────────────────────────────────────
        types.Tool(
            name="msg_react",
            description="Add a reaction to a message. Idempotent — calling twice with the same (message_id, agent_id, reaction) triple is safe and returns the existing reaction.",
            inputSchema={
                "type": "object",
                "properties": {
                    "message_id": {"type": "string", "description": "ID of the message to react to."},
                    "agent_id":   {"type": "string", "description": "ID of the reacting agent."},
                    "reaction":   {"type": "string", "description": "Reaction label, e.g. 'agree', 'disagree', 'important'."},
                },
                "required": ["message_id", "agent_id", "reaction"],
            },
        ),
        types.Tool(
            name="msg_unreact",
            description="Remove a reaction from a message. Returns removed=true if the reaction existed, false if it was already absent (safe to call even if not previously reacted).",
            inputSchema={
                "type": "object",
                "properties": {
                    "message_id": {"type": "string", "description": "ID of the message."},
                    "agent_id":   {"type": "string", "description": "ID of the agent removing their reaction."},
                    "reaction":   {"type": "string", "description": "The reaction label to remove."},
                },
                "required": ["message_id", "agent_id", "reaction"],
            },
        ),

        # ── Bus config ────────────────────────────────────────────────────
        types.Tool(
            name="bus_connect",
            description=(
                "One-step connect: register an agent and join (or create) a thread. "
                "Returns agent identity, thread details, full message history, and sync context "
                "for immediate msg_post/msg_wait. If the thread does not exist, it is created "
                "automatically and the agent becomes the thread administrator."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "thread_name": {"type": "string",
                                    "description": "Thread topic name to join or create."},
                    "ide":         {"type": "string",
                                    "description": "IDE name for new registration."},
                    "model":       {"type": "string",
                                    "description": "Model name for new registration."},
                    "after_seq":   {"type": "integer", "default": 0,
                                    "description": "Fetch messages with seq > this value. Default 0 (all)."},
                },
                "required": ["thread_name"],
            },
        ),
        types.Tool(
            name="bus_get_config",
            description=(
                "Get the bus-level configuration. "
                "Agents SHOULD call this once at startup. "
                "The most important field is `preferred_language`: agents are expected to "
                "try to communicate in that language whenever possible. "
                "This is a SOFT recommendation — no enforcement is done by the server. "
                "If not configured by the operator, defaults to 'English'.\n\n"
                "**Role Awareness:** When calling `bus_connect`, the response `agent` block now includes "
                "`is_administrator` (boolean) and `role_assignment` (natural language instruction "
                "containing the administrator's agent_id and name). If you are the administrator, "
                "coordinate tasks. If you are a participant, wait for instructions from the "
                "administrator mentioned in your `role_assignment`."
            ),
            inputSchema={"type": "object", "properties": {}},
        ),

        # ── Full-text search (UI-02) ──────────────────────────────────────
        types.Tool(
            name="msg_search",
            description=(
                "Full-text search across message content using SQLite FTS5. "
                "Returns relevance-ranked results with snippets. "
                "Optionally restrict to a single thread with thread_id."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "query":     {"type": "string", "description": "FTS5 MATCH expression, e.g. 'hello world' or 'angular*'."},
                    "thread_id": {"type": "string", "description": "Optional thread ID to restrict search scope."},
                    "limit":     {"type": "integer", "description": "Max results (default 50, max 200).", "default": 50},
                },
                "required": ["query"],
            },
        ),
        types.Tool(
            name="msg_edit",
            description=(
                "Edit the content of an existing message. "
                "Only the original author or 'system' can edit. "
                "The edited_by value is deduced from the connected agent identity. "
                "Preserves full version history in message_edits table. "
                "Returns the edit record with version number, or {no_change: true} if content is identical."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "message_id":  {"type": "string", "description": "ID of the message to edit."},
                    "new_content": {"type": "string", "description": "New content for the message."},
                },
                "required": ["message_id", "new_content"],
            },
        ),
        types.Tool(
            name="msg_edit_history",
            description=(
                "Retrieve the full edit history of a message. "
                "Returns all previous versions in chronological order (oldest first). "
                "Each entry contains old_content, edited_by, version, and created_at."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "message_id": {"type": "string", "description": "ID of the message."},
                },
                "required": ["message_id"],
            },
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[types.Content]:
    db = await get_db()

    import importlib
    import sys
    from src.config import RELOAD_ENABLED

    # Reload dispatch only in dev mode (hot-reload) — avoids arbitrary code
    # execution risk in production where source files should be immutable.
    if "src.tools.dispatch" in sys.modules:
        if RELOAD_ENABLED:
            importlib.reload(sys.modules["src.tools.dispatch"])
    else:
        import src.tools.dispatch

    return await sys.modules["src.tools.dispatch"].dispatch_tool(db, name, arguments)


# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
# RESOURCES
# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ

@server.list_resources()
async def list_resources() -> list[types.Resource]:
    db = await get_db()
    threads = await crud.thread_list(db, status=None)
    resources = [
        types.Resource(
            uri="chat://bus/config",
            name="Bus Configuration",
            description=(
                "Bus-level settings including the preferred language. "
                "Agents should read this at startup and try to comply with preferred_language."
            ),
            mimeType="application/json",
        ),
        types.Resource(
            uri="chat://agents/active",
            name="Active Agents",
            description="All currently registered agents and their online status.",
            mimeType="application/json",
        ),
        types.Resource(
            uri="chat://threads/active",
            name="Active Threads",
            description="Summary list of all threads.",
            mimeType="application/json",
        ),
    ]
    # Only expose per-thread resources if explicitly enabled via config
    if EXPOSE_THREAD_RESOURCES:
        for t in threads:
            resources.append(types.Resource(
                uri=f"chat://threads/{t.id}/transcript",
                name=f"Transcript: {t.topic[:40]}",
                description=f"Full conversation history for thread '{t.topic}'",
                mimeType="text/plain",
            ))
            if t.summary:
                resources.append(types.Resource(
                    uri=f"chat://threads/{t.id}/summary",
                    name=f"Summary: {t.topic[:40]}",
                    description=f"Closed-thread summary for '{t.topic}'",
                    mimeType="text/plain",
                ))
            resources.append(types.Resource(
                uri=f"chat://threads/{t.id}/state",
                name=f"State: {t.topic[:40]}",
                description=f"Current state snapshot for thread '{t.topic}' (status, latest_seq).",
                mimeType="application/json",
            ))
    return resources


@server.read_resource()
async def read_resource(uri: types.AnyUrl) -> str:
    db = await get_db()
    uri_str = str(uri)

    if uri_str == "chat://bus/config":
        session_lang   = _session_language.get()
        effective_lang = session_lang or "English"
        return json.dumps({
            "preferred_language": effective_lang,
            "language_source":    "url_param" if session_lang else "default",
            "language_note": (
                f"Please respond in {effective_lang} whenever possible. "
                "This is a soft preference ΓÇö use your best judgement."
            ),
            "bus_name": "AgentChatBus",
            "version":  BUS_VERSION,
            "endpoint": f"http://{HOST}:{PORT}",
        }, indent=2)

    if uri_str == "chat://agents/active":
        agents = await crud.agent_list(db)
        return json.dumps([
            {"agent_id": a.id, "name": a.name, "description": a.description,
             "capabilities": json.loads(a.capabilities) if a.capabilities else [],
             "skills": json.loads(a.skills) if a.skills else [],
             "is_online": a.is_online}
            for a in agents
        ], indent=2)

    if uri_str == "chat://threads/active":
        threads = await crud.thread_list(db)
        return json.dumps([
            {"thread_id": t.id, "topic": t.topic, "status": t.status,
             "created_at": t.created_at.isoformat()}
            for t in threads
        ], indent=2)

    # chat://threads/{id}/transcript
    if "/transcript" in uri_str:
        thread_id = uri_str.split("/")[3]  # Fixed: was [2] which was 'threads', should be [3] which is the ID
        t = await crud.thread_get(db, thread_id)
        if t is None:
            return "Thread not found."
        msgs = await crud.msg_list(db, thread_id, after_seq=0, limit=10000)
        lines = [f"# Thread: {t.topic}  [status: {t.status}]\n"]
        for m in msgs:
            lines.append(f"[seq={m.seq}] {m.author} ({m.role}): {m.content}")
        return "\n".join(lines)

    # chat://threads/{id}/summary
    if "/summary" in uri_str:
        thread_id = uri_str.split("/")[3]  # Fixed: was [2] which was 'threads', should be [3] which is the ID
        t = await crud.thread_get(db, thread_id)
        if t is None:
            return "Thread not found."
        return t.summary or "(No summary recorded for this thread.)"

    # chat://threads/{id}/state
    if "/state" in uri_str:
        thread_id = uri_str.split("/")[3]
        t = await crud.thread_get(db, thread_id)
        if t is None:
            return "Thread not found."
        latest_seq = await crud.thread_latest_seq(db, thread_id)
        return json.dumps({
            "thread_id": t.id,
            "topic": t.topic,
            "status": t.status,
            "latest_seq": latest_seq,
            "created_at": t.created_at.isoformat(),
        }, indent=2)

    return f"Unknown resource URI: {uri_str}"


# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
# PROMPTS
# ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ

@server.list_prompts()
async def list_prompts() -> list[types.Prompt]:
    return [
        types.Prompt(
            name="summarize_thread",
            description="Instructs an agent to produce a concise summary of a thread's transcript.",
            arguments=[
                types.PromptArgument(name="topic", description="The thread topic.", required=True),
                types.PromptArgument(name="transcript", description="The full transcript text.", required=True),
            ],
        ),
        types.Prompt(
            name="handoff_to_agent",
            description="Standard format for handing off a task from one agent to another.",
            arguments=[
                types.PromptArgument(name="from_agent", description="Name of the delegating agent.", required=True),
                types.PromptArgument(name="to_agent", description="Name of the receiving agent.", required=True),
                types.PromptArgument(name="task_description", description="What needs to be done.", required=True),
                types.PromptArgument(name="context", description="Relevant background or prior decisions.", required=False),
            ],
        ),
    ]


@server.get_prompt()
async def get_prompt(name: str, arguments: dict[str, str] | None) -> types.GetPromptResult:
    args = arguments or {}

    if name == "summarize_thread":
        return types.GetPromptResult(
            description="Summarize the thread transcript.",
            messages=[types.PromptMessage(
                role="user",
                content=types.TextContent(type="text", text=(
                    f"Please read the following conversation transcript for the topic "
                    f"\"{args.get('topic', '(unknown)')}\" and write a concise summary "
                    f"capturing the key decisions, conclusions, and any open questions.\n\n"
                    f"--- TRANSCRIPT ---\n{args.get('transcript', '')}\n--- END ---"
                )),
            )],
        )

    if name == "handoff_to_agent":
        context_block = f"\n\nRelevant context:\n{args['context']}" if args.get("context") else ""
        return types.GetPromptResult(
            description="Task handoff message.",
            messages=[types.PromptMessage(
                role="user",
                content=types.TextContent(type="text", text=(
                    f"Hi {args.get('to_agent', 'Agent')}, this is {args.get('from_agent', 'Agent')} handing off a task to you.\n\n"
                    f"**Task:** {args.get('task_description', '')}{context_block}\n\n"
                    f"Please acknowledge and proceed."
                )),
            )],
        )

    raise ValueError(f"Unknown prompt: {name}")